# Generated by Django 5.0.1 on 2025-01-23 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Unique identifier for the category (used in URLs).', unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.ForeignKey(help_text='Category of the game.', on_delete=django.db.models.deletion.CASCADE, related_name='games', to='games.category'),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(help_text='A brief description of the game.'),
        ),
        migrations.AlterField(
            model_name='game',
            name='embed_code',
            field=models.TextField(help_text='Embed code for the game iframe (e.g., CrazyGames).'),
        ),
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.FloatField(default=0.0, help_text='Average user rating (out of 5).'),
        ),
        migrations.AlterField(
            model_name='game',
            name='thumbnail_url',
            field=models.URLField(help_text="URL of the game's thumbnail image."),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(help_text='Title of the game.', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0, help_text='Total number of reviews for the game.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(help_text="User's comment for the game."),
        ),
        migrations.AlterField(
            model_name='review',
            name='game',
            field=models.ForeignKey(help_text='Game being reviewed.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='games.game'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(help_text='Rating for the game (e.g., 1-5 stars).'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(help_text='User who submitted the review.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('game', 'user')},
        ),
    ]
